# Generated by Django 5.0.4 on 2024-06-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_categories_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bloger',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
