# Generated by Django 5.0.4 on 2024-06-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_bloger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bloger',
            new_name='blogger',
        ),
    ]
