# Generated by Django 5.0.4 on 2024-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_bloger_blog_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imageFile',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
