# Generated by Django 5.0.4 on 2024-06-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
