# Generated by Django 5.0.4 on 2024-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imageFile',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/'),
        ),
    ]
